language: node_js
node_js:
  - "10"
  - "8"
  - "6"
  - "4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm i -g npm@^2

cache:
  yarn: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - npm install
  - yarn install
