language: node_js
node_js:
  - "10"
  - "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm i -g npm

cache:
  yarn: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - npm install
  - yarn install
