environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"

platform:
  - x86
  - x64

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version

build: off